version: '3.7'

# Define services
services:
  backend:
    depends_on:
      - app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8083"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
    networks:
      - backend

  app:
    container_name: app
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    #    volumes:
    #      - ./data/mysql:/var/lib/mysql/data
    networks:
      - backend

  #Docker Networks
networks:
  backend:
    driver: bridge

  #Volumes
volumes:
  dbdata:
    driver: local