version: "3"
services:
  backend:
    container_name: backend
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demo
      SPRING_DATASOURCE_USERNAME: demo_user
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - postgres
    networks:
      - api

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: demo_user
      POSTGRES_DB: demo
    networks:
      - api

volumes:
  postgres-data:

networks:
  api:




